name: Run YAML on PR

on:
  push:
    branches:
      - '*'

jobs:
  main_job:
    if: ${{ github.head_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print staff
        run: echo "Here is Main branch"

  mylo_job:
    if: ${{ github.head_ref == 'mylo' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print staff
        run: echo "Here is mylo branch"

  deel_job:
    if: ${{ github.head_ref == 'deel' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print staff
        run: echo "Here is deel branch"
