name: Run YAML on PR
on:
  push:
    branches:
      - '*'
jobs:
  main_job:
    if: ${{ github.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is Main branch"
  mylo_job:
    if: ${{ github.ref == 'mylo' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is mylo branch"
        
  deel_job:
    if: ${{ github.ref == 'deel' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is deel branch"
