name: My Workflow
'on':
  push:
    branches:
      - main
      - mylo
      - deel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - if: '${{ github.ref == ''refs/heads/main'' }}'
        name: Build and deploy to main branch
        run: npm run build && npm run deploy
      - if: '${{ github.ref == ''refs/heads/mylo'' }}'
        name: Run tests on mylo branch
        run: npm run test
      - if: '${{ github.ref == ''refs/heads/deel'' }}'
        name: Deploy to deel branch
        run: 'npm run deploy:deel'
