name: Run YAML on PR

on:
  push:
    branches:
      - main
      - mylo
      - deel


jobs:   
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
  mylo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is mylo branch"
        
  deel_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is deel branch"
