name: Auto Version and Release
"on":
  push:
    branches:
      - main
jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to Fiber-iOS
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        working-directory: ${{ github.workspace }}
        run: |
          git config --global user.name 'YousefBtech'
          git config --global user.email 'yousef.hanafi@btech.com'
          git clone -b preprod https://user:$GH_TOKEN@github.com/btechlabs/fiber-ios.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/FiberDesignSystem/Fiber/DesignSystem/DesignSystemTypes.swift
          cp DesignSystemTypes.swift fiber-ios-temp/Sources/FiberDesignSystem/Fiber/DesignSystem/
          rm -rf fiber-ios-temp/Sources/FiberRetail/DesignSystemValues.swift
          cp DesignSystemValues.swift fiber-ios-temp/Sources/FiberRetail/
          rm -rf fiber-ios-temp/Sources/FiberDesignSystem/Resources/Assets/Colors.xcassets
          cp -r Colors.xcassets fiber-ios-temp/Sources/FiberDesignSystem/Resources/Assets/
          rm -rf fiber-ios-temp/Sources/FiberRetail/Resources/Colors.xcassets
          cp -r Colors.xcassets fiber-ios-temp/Sources/FiberRetail/Resources/
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem files from fiber-core"
          git push
          gh pr create --base main --head preprod --title "chore: Update design system values" --body "Your Pull Request Description"
