name: Auto Version and Release
'on':
  push:
    branches:
      - main
jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Push to Fiber-iOS
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'YousefBtech'
          git config --global user.email 'yousef.hanafi@btech.com'
          git clone -b retail https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-iOS.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/Fiber-iOS/DesignSystemTypes.swift
          cp DesignSystemTypes.swift fiber-ios-temp/Sources/Fiber-iOS/
          rm -rf fiber-ios-temp/Sources/Fiber-iOS/DesignSystemValues.swift
          cp DesignSystemValues.swift fiber-ios-temp/Sources/Fiber-iOS/
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          git push 
      - name: Create Pull Request using cURL
        run: |
          REPO="YousefBtech/fiber-iOS"
          BODY="{
            \"title\": \"Pull Request Title\",
            \"head\": \"retail\",
            \"base\": \"main\",
            \"body\": \"Pull Request Description\"
          }"
          curl -X POST \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$BODY" \
            "https://api.github.com/repos/$REPO/pulls"
