name: Run YAML on PR
'on':
  push:
    branches:
      - '!main'
      - 'mylo'
      - 'deel'
jobs:
  main_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is Main branch"
  mylo_job:
    if: ${{ github.ref == 'refs/heads/mylo' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is mylo branch"
  deel_job:
    if: ${{ github.ref == 'refs/heads/deel' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print staff
        run: echo "Here is deel branch"
