name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'  # Specify the Swift version you are using

      - name: Build and test
        run: |
          swift build
          swift test

      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Release notes for version ${{ steps.get_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Get release version
        run: echo "The new release version is ${{ steps.get_tag.outputs.tag }}"
