name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'  # Specify the Swift version you are using

      - uses: abdelrhmanElmhdy/setup-xcode@v1.7.0
        with:
          xcode-version: 15.0.1
          
      - name: Build and test
        run: |
          swift build
          swift test

      - name: Get the latest commit hash
        id: get_commit_hash
        run: echo ::set-output name=commit_hash::$(git rev-parse --short HEAD)

      - name: Create Git tag
        id: create_tag
        run: |
          git tag -a v${{ steps.get_commit_hash.outputs.commit_hash }} -m "Version ${{ steps.get_commit_hash.outputs.commit_hash }}"
          git push origin v${{ steps.get_commit_hash.outputs.commit_hash }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_commit_hash.outputs.commit_hash }}
          release_name: Release ${{ steps.get_commit_hash.outputs.commit_hash }}
          body: |
            Release notes for version ${{ steps.get_commit_hash.outputs.commit_hash }}
          draft: false
          prerelease: false

      - name: Get release version
        run: echo "The new release version is ${{ steps.get_commit_hash.outputs.commit_hash }}"
