name: Main Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add the rest of your build steps here
      - name: Your Build Step
        run: echo "Perform your build steps here"
