name: Auto Version and Release
'on':
  push:
    branches:
      - main
jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Push to Fiber-iOS
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        working-directory: ${{ github.workspace }} 
        run: |
          git config --global user.name 'YousefBtech'
          git config --global user.email 'yousef.hanafi@btech.com'
          git clone -b retail https://user:$ACCESS_TOKEN@github.com/YousefBtech/fiber-iOS.git fiber-ios-temp
          rm -rf fiber-ios-temp/Sources/Fiber-iOS/DesignSystem.swift
          cp DesignSystemTypes.swift fiber-ios-temp/Sources/Fiber-iOS/
          cp DesignSystemValues.swift fiber-ios-temp/Sources/Fiber-iOS/
          cd fiber-ios-temp
          git add .
          git commit -m "Copy DesignSystem.swift from fiber-core"
          git push 
      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          branch: retail
          base: main
          commit-message: 'Automatically generated PR'
          title: 'Automatically generated PR'
          body: 'This PR was automatically generated by a GitHub Action.'
