name: Auto Version and Release

on:
  push:
    branches:
      - main

jobs:
  bump-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          git config --local user.email "yousef.hanafi@btech.com"
          git config --local user.name "YousefBtech"
          git tag v$(cat VERSION)
          git push origin v$(cat VERSION)

